### ISSUE TITLE
How to catch errors from the web worker ?

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/worker-pouch#10]
I spent some time to indetify some errors occured inside the webworker due to wrong options datas.
is there a way to catch these errors ?

**Comment by nolanlawson** [comment]
worker-pouch is not really designed to handle worker errors for you. If you look at the console in Chrome, though, you can usually see them there. Another option is to open up the debugger and tick "break on exceptions."

Closing, since this is out of scope for worker-pouch.
