### ISSUE TITLE
Error Failed to Execute 'PostMessage'

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/worker-pouch#12]
When Getting some data the cloning is not possible on the worker side.

![image](https://cloud.githubusercontent.com/assets/7273443/13203463/18c00404-d8b9-11e5-8030-81404f189f2b.png)

**Comment by ronyrun** [comment]
I solved my issue with a cloning of the doc before saving into the worker DB.

**Comment by nolanlawson** [comment]
Yes, objects cannot be cloned if they have functions inside of them. PouchDB ignores this; worker-pouch throws an error when this happens.

**Comment by ronyrun** [comment]
In my case I just did a _.clone(device) in order to make it work.
