### ISSUE TITLE
example local.replicate.to: "Cannot read property 'to' of undefined"

### ISSUE THREAD

**Issue by schamp** [nolanlawson/worker-pouch#13]
I am trying the basic replication example, as given in the readme (using browserify, in angular, if that makes any difference):  
```
'use strict'

const PouchDB = require('pouchdb')
const workerPouch = require('worker-pouch')

function DataService ($http, $q, Config) {
  var local = new PouchDB('local', {adapter: 'worker'})
  local.replicate.to('http://localhost:5984/local-test')
...
}
```

but I am receiving "Cannot read property 'to' of undefined", on the 'replicate' property of local.

Am I missing something about how to set this up?

I am primarily interested in replicating *from* a remote within the worker, but I figured I should at least get the example working as written.

```
$ npm list pouchdb worker-pouch
...
├── pouchdb@5.3.0
└── worker-pouch@1.0.1
```

**Comment by nolanlawson** [comment]
I think you forgot to do:

```js
PouchDB.adapter(workerPouch);
```

Can you add that and check if it works?

**Comment by schamp** [comment]
That seems to have done it, must have passed over that part of the instructions.  Thanks!
