### ISSUE TITLE
Worker-Pouch not working with new pouchdb version 6.0.4

### ISSUE THREAD

**Issue by ajinkyau** [nolanlawson/worker-pouch#27]
Hi,

I have updated to the latest pouchdb version & noticed that the worker-pouch which I have been using with the old pouchdb version 5.4.5 is not working with this new version.

Wanted to know what might be the problem here & when can this be fixed?

Thanks,
Ajinkya

**Comment by SinanGabel** [comment]
Hi!

I also just noticed the same! Have not had time to dig into it yet.

Thanks!

**Comment by nolanlawson** [comment]
Thanks for reporting. socket-pouch probably has this issue too.

**Comment by ajinkyau** [comment]
Any update on this issue?

**Comment by nolanlawson** [comment]
Nope I am swamped right now and would appreciate all the help I can get. 😅

**Comment by nolanlawson** [comment]
fixed in #30
