### ISSUE TITLE
[Request] Client side implementation

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/worker-pouch#3]
Hello,

Is is possible to have a client web side implementation example ?
(bower, etc...)

**Comment by nolanlawson** [comment]
Bower is becoming more and more unrecommended for anything in web development. If you need to use this module, I support npm or you can also browserify it using wzrd.in, e.g.: wzrd.in/standalone/worker-pouch@latest

The npm package should contain a `dist/` folder with everything you need, cheers.
