### ISSUE TITLE
Unable to get the changes - worker and db.changes

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/worker-pouch#9]
When testing the db.changes with the worker adapter : 

I encounter a strange behavior with my chrome desktop and the chrome Android in regard to the paste.pouchdb.com.

When using the test script on this site (available here) : http://paste.pouchdb.com/paste/1df1i5
I can see in the console logs that the db.changes listener is working.

![image](https://cloud.githubusercontent.com/assets/7273443/13111882/a0d586e0-d588-11e5-99d7-4813bf9a439e.png)

When I use this code on my Ionic APP client The db.changes listener is not working.

Do you know what is going on, and why I encounter this issue ? ?

Regards,
Ron

**Comment by ronyrun** [comment]
I created a testWorker3.html file and opened it on Firefox and Chrome.
When Testing it on my Ionic App, I also have the same problem.

**Comment by ronyrun** [comment]
The script is working when using a webServer for the execution.
I'm retesting on Ionic.

Currently on my app, the db.changes doesn't work at all.

**Comment by ronyrun** [comment]
This is the result of the script on the Ionic APP (I replaced the current index.html with the script  http://paste.pouchdb.com/paste/1df1i5)

I'm don't have the db.changes results

![image](https://cloud.githubusercontent.com/assets/7273443/13116776/6ad5f006-d59d-11e5-8427-7bf1641159d7.png)

**Comment by nolanlawson** [comment]
I'm sorry, can you please provide some simple steps to reproduce? I don't understand what the problem is, or how to reproduce it.

E.g. fill out this form:

1. Steps to reproduce
2. Expected result
3. Actual result
4. Platform, browser, etc.

**Comment by ronyrun** [comment]
I'm on it

**Comment by ronyrun** [comment]
I'm getting the localDB object through a AngularJS Service.
it is maybe the origin of the pb.

When I declaring the db.changes straight after the creation it is working fine.

**Comment by ronyrun** [comment]
I found the problem.

I wasn't able to see error inside the web worker.
I implemented an external variable in the filter property of the db.changes.
and the web worker wasn't able to get it, and I did not have any errors :)
